---
- include: common.yml

# This is a setup for vagrant host, inherits from all
- hosts: default
  become: yes
  roles:
    - { role: mysql, use_mysql56: true }
    - { role: php, use_php56: true, use_xdebug: true, use_xdebug_profiler: true }
    - { role: composer, use_composer_no_dev: no }
    - { role: mongodb, use_php: true }
    - { role: nginx, use_php: true }

  handlers:
    - include: roles/nginx/handlers/main.yml

  tasks:
    - name: Update bashrc for with the app environment
      lineinfile:
        dest=/home/vagrant/.bashrc
        line="export APPLICATION_ENVIRONMENT=development"
        regexp='^export APPLICATION_ENVIRONMENT=development$'
        state=present
        insertafter=EOF
        create=True
    - name: Install the valgrind (APT)
      apt: name=valgrind state=latest update_cache=yes
